auth:
    resource: ../src/Auth/Infrastructure/Symfony/Routes/auth.yaml

team:
    resource: ../src/Team/Infrastructure/Symfony/Routes/team.yaml

project:
    resource: ../src/Project/Infrastructure/Symfony/Routes/project.yaml

sprint:
    resource: ../src/Sprint/Infrastructure/Symfony/Routes/sprint.yaml

ticket:
    resource: ../src/Ticket/Infrastructure/Symfony/Routes/ticket.yaml
